added github action job to validate terraform code

diff --git a/.github/action-terraform-verify.yml b/.github/action-terraform-verify.yml
--- a/.github/action-terraform-verify.yml
+++ b/.github/action-terraform-verify.yml
@@ -50,3 +50,28 @@ jobs:
       - name: Process check
         if: always()
         run: exit $CHECK_STATUS
+
+  validate1:
+    runs-on: ubuntu-latest
+    name: Validate Terraform module
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        run: |
+          set +e
+
+          echo "CHECK_STATUS=0" >> $GITHUB_ENV
+
+          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
+            echo "Checking terraform fmt on ${changed_file}..."
+
+            if [[ $changed_file == *.tf ]]; then
+              terraform fmt -check $changed_file
+              FMT_STATUS=$(echo $?)
+
+              if [[ $FMT_STATUS -ne 0 ]]; then
+                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
+                echo "CHECK_STATUS=1" >> $GITHUB_ENV
+              fi
+            fi
+          done
